@ServiceMonitor_API_HostAddress = http://localhost:5100

GET {{ServiceMonitor_API_HostAddress}}/api/services/4
Accept: application/json

###

GET {{ServiceMonitor_API_HostAddress}}/api/services
Accept: application/json

###

POST {{ServiceMonitor_API_HostAddress}}/api/services
Content-Type: application/json

{
  "Name": "YouTube",
  "Endpoint": "https://www.youtube.com/",
  "CheckIntervalMinutes": 2
}

###

PUT {{ServiceMonitor_API_HostAddress}}/api/services
Content-Type: application/json

{
  "Id": 4,
  "Endpoint": "https://notvalidurl..."
}

###

DELETE {{ServiceMonitor_API_HostAddress}}/api/services/4
Accept: application/json
