@ServiceMonitor_API_HostAddress = http://localhost:5100
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InRlc3R0ZXN0IiwiZW1haWwiOiJ0ZXN0dGVzdEB0ZXN0LmNvbSIsImp0aSI6IjAxZDZkMTAxLWRiY2UtNGQwYi05YjA3LTYzMWE1OTUwODdlYiIsInJvbGUiOiJVc2VyIiwibmJmIjoxNzc5MTMzNDk5LCJleHAiOjE3NzkxMzQzOTksImlhdCI6MTc3OTEzMzQ5OSwiaXNzIjoiU2VydmljZU1vbml0b3JBUEkiLCJhdWQiOiJTZXJ2aWNlTW9uaXRvckNsaWVudCJ9.BZ6FiPlLaaZ-lBWfzYmezFJH5zz6uDE7x1AMoPhVkpo

GET {{ServiceMonitor_API_HostAddress}}/api/services
Accept: application/json
Authorization: Bearer {{token}}

###

GET {{ServiceMonitor_API_HostAddress}}/api/services
Accept: application/json

###

POST {{ServiceMonitor_API_HostAddress}}/api/services
Content-Type: application/json

{
    "Name": "YouTube",
    "Endpoint": "https://www.youtube.com/",
    "CheckIntervalMinutes": 2
}

###

PUT {{ServiceMonitor_API_HostAddress}}/api/services
Content-Type: application/json

{
    "Id": 4,
    "Endpoint": "https://notvalidurl..."
}

###

DELETE {{ServiceMonitor_API_HostAddress}}/api/services/4
Accept: application/json

###

POST {{ServiceMonitor_API_HostAddress}}/api/auth/register
Content-Type: application/json

{
    "email": "testtest@test.com",
    "password": "Password1@"
}

###

POST {{ServiceMonitor_API_HostAddress}}/api/auth/login
Content-Type: application/json

{
    "email": "testtest@test.com",
    "password": "Password1@"
}
